//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Customer
    {
        public int CustomerId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Payment { get; set; }
        public string Description { get; set; }
        public string Level { get; set; }
        public string Type { get; set; }
        public string Flag { get; set; }
    }
}
